package util;

public enum Commands {
	FETCH_ORDERS, FETCH_PRODUCTS, FETCH_BRANCHES,FETCH_ITEMS,FETCH_ALL_USERS_DETAILS,FETCH_SURVEYS, SERVER_DISCONNEDTED,
	CLIENT_DISCONNECTED, LOGOUT, LOGIN, CHANGE_USER_STATUS, INSERT_ACCOUNT_PAYMENT, INSERT_ORDER, INSERT_ORDERS_PRODUCT,
	INSERT_DELIVERY, INSERT_DELIVERY_ORDER,GET_SERVEY,SUBMIT_SURVEY, SUBMIT_COMPLAINT, INSERT_ORDERS_ITEMS,UPDATE_PRODUCTS_BASE,
	GET_ORDER_NUMBERS, FETCH_COMPLAINTS, CLOSE_COMPLAINT, GET_ORDER_SUM, NEW_USER_DETAILS, NEW_USERS,
	DELETE_USER_DETAILS, FETCH_ORDERS_MANAGER, APPROVE_ORDER, CANCEL_ORDER, FETCH_NOTIFICATIONS, INSERT_CUSTOM_PRODUCTS,
	INSERT_CUSTOM_PRODUCT_PRODUCTS, INSERT_CUSTOM_PRODUCT_ITEMS, INSERT_ORDER_CUSTOM_PRODUCTS;
}
