package util;

public enum NotificationType {
	COMPLAINT_DUE,ORDER_ACCEPTED,ORDER_CANCELED_REFUND,DELIVERY_LATE_REFUND,REGISTRATION_DISCOUNT, CANCEL_REQUEST_DENIED, CANCEL_REQUEST_APPROVED, ORDER_NOT_ACCEPTED;
}
