package util;

public enum Screens {
	GUEST_HOME, USER_HOME, CATALOG, PRODUCT_DETAILS_POPUP, CLIENT, VIEW_ORDERS, LOGIN, CART, CHECKOUT, DELIVERY_DETAILS,
	GREETING_CARD, PAYMENT_SUCCESSFULY, REPORT, VIEW_COMPLAINTS_REPORT, VIEW_INCOME_REPORT, VIEW_ORDERS_REPORT,
	MANAGE_USERS, SURVEY_HOME, SURVEY, COMPLAINT_HOME, COMPLAINT,EDIT_CATALOG,CUSTOM_PRODUCT_BUILDER, COMPLAINT_VIEW, CATALOG_SPLASH_SCREEN, REGISTER_CUSTMER, VIEW_ORDERS_MANAGER, VIEW_ORDERS_CUSTOMER;

}
